FROM node:20

WORKDIR /app

COPY package.json yarn.lock tsconfig.json ./
RUN yarn install

COPY public ./public
COPY src ./src
COPY next.config.ts ./

RUN yarn build

EXPOSE 3000
CMD ["yarn", "start"]
